[package]
name = "arraylib_macro"
version = "0.1.0"
edition = "2021"

[lib]
name = "arraylib_macro"
proc-macro = true

[dependencies]
syn = { version = "^2.0", features = ["full", "parsing"] }
proc-macro2 = "^1.0"
quote = "^1.0"