[package]
name = "arraylib"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.16.0", features = ["extern_crate_std", "derive", "min_const_generics"] }
num = "0.4.3"
serde = { version = "^1.0", features = ["derive"] }
zerocopy = { version = "0.7.34", features = ["byteorder", "alloc", "derive"] }
